# Generated by Django 4.1.7 on 2023-08-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguoidung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgUrl',
            field=models.ImageField(blank=True, default='regex.png', upload_to='img'),
        ),
    ]
