# Generated by Django 4.2.1 on 2023-08-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nguoidung', '0002_post_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imgUrl',
            field=models.ImageField(blank=True, default='1109355.jpg', upload_to=''),
        ),
    ]
